# Copyright Jiaqi Liu
---
name: CI/CD

'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  documentation:
    name: Tests documentation build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: |     
          gem install jekyll
          bundle install
          bundle exec rake build
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          enable_jekyll: false
          user_name: QubitPi
          user_email: jack20220723@gmail.com
